### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by mr-c** [ParkerLab/ataqv#12]
I saw an article use https://doi.org/10.1038/ncomms1176 as the citation for `ataqv`, but I thought I'd confirm directly.

**Comment by porchard** [comment]
Thanks for asking. I have no clue why someone would have cited that manuscript. For the moment, a link to this GitHub is all we have -- so maybe something like "A toolkit for QC and visualization of ATAC-seq results. https://github.com/ParkerLab/ataqv (2017). Accessed 26 Oct 2017." We are working on getting the software officially published, so hopefully that will change soon. Once it's published, I'll update the GitHub to point to the manuscript.

**Comment by mr-c** [comment]
Okay! I just submitted my packaging of ataqv to Debian. We'll add your paper citation to our metadata records when you're ready.

https://ftp-master.debian.org/new/ataqv_1.1.1+ds-1.html

If you don't have a journal in mind to submit to, I recommend https://joss.theoj.org/

**Comment by porchard** [comment]
Thanks! Ataqv is now published in Cell Systems: https://doi.org/10.1016/j.cels.2020.02.009
