### ISSUE TITLE
ncurses.h: No such file or directory

### ISSUE THREAD

**Issue by CherryZhang-22y** [ParkerLab/ataqv#18]
I want to install ataqv, but it showed that I didn't install ncurses. After I did install the ncurses, it still showed the same problem. The ubuntu I used is 18.0.4.

root@zju-ThinkStation-P520c:/home/zju/ataqv# make
/home/zju/miniconda2/bin/x86_64-conda_cos6-linux-gnu-c++ -std=c++11 -pthread -O3 -g -pedantic -Wall -Wextra -Wwrite-strings -Wstrict-overflow -fno-strict-aliasing -fPIC -I/home/zju/ataqv/src/cpp -D AMD64 -D LINUX -o build/ataqv.o -c /home/zju/ataqv/src/cpp/ataqv.cpp
/home/zju/ataqv/src/cpp/ataqv.cpp:12:10: fatal error: ncurses.h: No such file or directory
 #include <ncurses.h>
          ^~~~~~~~~~~
compilation terminated.

Thanks for help!!!

**Comment by porchard** [comment]
Thanks @umijh -- updated the README and Debian control file in the newest commit.

**Comment by porchard** [comment]
Closing as this should hopefully no longer be a problem -- please re-open if necessary.
