### ISSUE TITLE
Segmentation fault (core dumped) during 'Calculating TSS coverage'

### ISSUE THREAD

**Issue by AlexBlais74** [ParkerLab/ataqv#19]
Hello
Started using ataqv (version 1.2.1), it seems to run fine until the TSS coverage analysis:

Calculating TSS coverage...
Added TSS coverage for chr19; thread count=1
Added TSS coverage for chr18; thread count=2
Added TSS coverage for chr17; thread count=3
Added TSS coverage for chr16; thread count=4
Added TSS coverage for chr15; thread count=5
Added TSS coverage for chr14; thread count=6
Added TSS coverage for chr13; thread count=7
Added TSS coverage for chr12; thread count=8
Added TSS coverage for chr11; thread count=9
Segmentation fault (core dumped)

This happens no matter if I use the provided TSS bed file or my own. Also happens with no specified number of threads.  Skipping the TSS analysis leads to a successful run. 

Usually when I get a segmentation fault (with other programs) it relates to the amount of memory available but I am running this with 50 Gb of RAM available. I am running on a large cluster, dependencies were loaded as modules, and compilation from source did not generate any error. 

Thanks in advance for your help.

Alex

**Comment by porchard** [comment]
Hi Alex, so this occurs even when you run it without passing any `--threads` argument? Can you share the command that you're running?

**Comment by AlexBlais74** [comment]
Hello
Thanks for your reply. 
Yes, it happens even without the --threads option.
Here is my command with setting threads to 9 (I have 10 cores reserved on the cluster with salloc) :
`~/projects/def-ablai2/ataqv/build/./ataqv \
--verbose \
--threads 9 \
--peak-file ~/projects/def-ablai2/project_path/peak_list.bed \
--tss-file ~/projects/def-ablai2/ataqv/data/tss/mm9.tss.refseq.bed.gz \
--excluded-region-file ~/projects/def-ablai2/Genomes/mm9/mm9-blacklist.bed \
--metrics-file LRBS11.ataqv.json \
mouse \
~/projects/def-ablai2/project_path/bam_and_bai_files/LRBS11.mm9.star.nodups.bam
`
The error message:
[snip]
Analyzed 36600000 reads in 154.674 seconds (236627 reads/second).
Analyzed 36700000 reads in 154.809 seconds (237066 reads/second).
Calculating TSS coverage...
Added TSS coverage for chr19; thread count=1
Added TSS coverage for chr18; thread count=2
Added TSS coverage for chr17; thread count=3
Added TSS coverage for chr16; thread count=4
Added TSS coverage for chr15; thread count=5
Added TSS coverage for chr14; thread count=6
Added TSS coverage for chr13; thread count=7
Added TSS coverage for chr12; thread count=8
Added TSS coverage for chr11; thread count=9
Segmentation fault (core dumped)

And the command without any threads specified:
`~/projects/def-ablai2/ataqv/build/./ataqv \
--verbose \
--peak-file ~/projects/def-ablai2/project_path/peak_list.bed \
--tss-file ~/projects/def-ablai2/ataqv/data/tss/mm9.tss.refseq.bed.gz \
--excluded-region-file ~/projects/def-ablai2/Genomes/mm9/mm9-blacklist.bed \
--metrics-file LRBS11.ataqv.json \
mouse \
~/projects/def-ablai2/project_path/bam_and_bai_files/LRBS11.mm9.star.nodups.bam
`
And the error message:
[snip]
Analyzed 36600000 reads in 152.633 seconds (239791 reads/second).
Analyzed 36700000 reads in 152.768 seconds (240233 reads/second).
Calculating TSS coverage...
Added TSS coverage for chr19; thread count=1
Segmentation fault (core dumped)

Thank you
Alex

**Comment by porchard** [comment]
Hi Alex,

Would you be able to share these files with me (e.g., via Google Drive/Dropbox)?

**Comment by AlexBlais74** [comment]
Sure I can do that. I tried replacing the peaks file with the tss bed file that comes with ataqv (in case my peak file was the culprit) and got the same error. I also suppose my BAM file is not malformed, since only the TSS analysis fails but the rest of the ataqv analyses run okay.  I would like to send that privately but I am not sure how this is done on Github. Can you email me: ablai2 at uottawa.ca

**Comment by AlexBlais74** [comment]
As an update, I have tried with a different, very small BAM file (100k read pairs) and also a different BED file, and I am getting the same segmentation fault.

**Comment by AlexBlais74** [comment]
Following your suggestion, I included the --ignore-read-groups option and the analysis completed without any problem. Thanks for the suggestion.
Alex

**Comment by porchard** [comment]
Fixed in newest commit (172bcd2)
