### ISSUE TITLE
ataqv memory segmentation error

### ISSUE THREAD

**Issue by jfertaj** [ParkerLab/ataqv#2]
Hi,

I have installed the ataqv binay from the tar.gz file and installed them in my Ubuntu 14.04 server, I have set-up the ataqv path to my $PATH and run `ataqv` with no commands to obtain the help, it worked however when I run with the full command: `ataqv --peak-file WTCHG_367049_05.hqaa.bam.macs2_peaks.broadPeak --metrics-file WTCHG_367049_05.md.bam.json.gz --library-description "" --description "" "human" WTCHG_367049_05.md.bam > WTCHG_367049_05.md.bam.ataqv.out'
 
I got the following error

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

Any ideas? I have 128GB of RAM free

**Comment by umijh** [comment]
I think this was just a bug that was fixed in the latest release. Sorry it took so long to get that out the door. Try the latest release (I rolled a new .deb) and let me know if you're still getting the error.

**Comment by umijh** [comment]
I'm going to close this as I'm pretty sure the problem was resolved in the latest release.  If I'm wrong, just leave a comment and I'll reopen the issue. Thanks for the report.
