### ISSUE TITLE
TSS bed causes segfault

### ISSUE THREAD

**Issue by ArielPaulson** [ParkerLab/ataqv#20]
Hi,

I have used both precompiled, and built from source (CentOS7), using current available code as of today.  In both cases, use of --tss-file segfaults, without any other message, immediately after the bam is loaded.  I am using mouse Ensembl 91 TSSs and have tried many different bed file configurations (3 column, 6 column, one per transcript, one per unique TSS, different sort orders, etc), to no avail.  

Without --tss-file, things work fine.

Thanks,
Ariel

**Comment by porchard** [comment]
Hi Ariel,

Can you share the command you're running, and would it be possible to share your BAM file (perhaps heavily downsampled, if such a file still results in the error)?

**Comment by ArielPaulson** [comment]
I have downsampled both the bam (100k reads) and the TSS file (1000).  Command is: ataqv-1.2.1/bin/ataqv --tss-file TSS2.bed mouse bowtie2.downsampled.bam

[data.tar.gz](https://github.com/ParkerLab/ataqv/files/5233702/data.tar.gz)

Thanks,
Ariel

**Comment by porchard** [comment]
Hi Ariel,

Peeking at the header of that BAM file, I see no read groups defined, and I'm wondering if this is in fact the same issue that was raised by issue #19 -- if there are no readgroups defined but the `--ignore-read-groups` flag is not set, a segfault will occur. I still need to update ataqv to fix that. For now, can you re-run your command with that flag, and see if it finishes?

**Comment by ArielPaulson** [comment]
Well that was it!  So --peak-file doesn't need read groups, but --tss-file does?

**Comment by porchard** [comment]
Hi Ariel,

Great, glad that solved the issue. Peak overlap and TSS enrichment can both be calculated on a per read group basis, and really the proper behavior in the case that no read groups are defined should be to ignore read groups regardless of whether or not the `--ignore-read-groups` flag is set. I'll get that fixed and push an update.

**Comment by porchard** [comment]
Fixed in newest commit (172bcd2)

**Comment by josruirod** [comment]
I can confirm this is solved with current version adding --ignore-read-groups, thanks
