### ISSUE TITLE
issue regarding the output html file 

### ISSUE THREAD

**Issue by vidarmehr** [ParkerLab/ataqv#26]
Dear ataqv software developers,

I am using ataqv to examine my ATAC-seq data in BAM format. I successfully ran your code and obtained a JSON file. Then I ran mkarv on the JSON file to generate the HTML file and other outputs. Everything seems to work properly. However, when I open the HTML file with internet explorer, google chrome or safari, I don't see the plots and tables. 
I receive the message "Internet Explorer restricted this webpage from running scripts or ActiveX controls". I click on "Allow blocked content", but still I am unable to see the plots.

I have also changed the security settings of Internet Explorer and enabled "Allow active content to run in files on My Computer" in Tools/Advanced and also I have enabled all options in "ActiveX controls and plug-ins group" in Tools/Security/Custom level. But, still, I am unable to see the plots/tables.

Could you please let me know if you have any solution for this problem? Sorry if this problem is not related to your software and could be related to my browser. But, I was wondering if you could help me with that. 

Thank you very much!
Vida

**Comment by porchard** [comment]
Hi Vida,

Sounds like it could be a browser issue. To verify that the files otherwise look as expected -- are you able to share the ataqv JSON(s) or the ataqv viewer directory? If so, I'll verify that it works on my end.

Best,

Peter

**Comment by vidarmehr** [comment]
Hi Peter,
Thank you very much for your response. 

Yes, that would be a great help. I appreciate it. I will send you the JSON files to parkerlab-software@umich.edu.

Thanks and regards,
Vida

**Comment by vidarmehr** [comment]
Dear Peter,

Thank you so much for your help to solve the issue that I had! 

Best
Vida

**Comment by EllenvdL** [comment]
Dear @vidarmehr,

I am currently having the same issue as you described. Do you still know how it was solved?

Best,
Ellen

**Comment by porchard** [comment]
Hi Ellen,

The issue was that in order to view the ataqv html report, you need to download the entire ataqv output directory -- if you just download the index.html file alone and open it in your browser, it'll be missing the data files it needs to read to generate the plots / tables

Let me know if that fixes the issue?

Best,

Peter

**Comment by vidarmehr** [comment]
@porchard: Thanks Peter for explaining the solution! I was trying to remember how the issue was solved :)

**Comment by EllenvdL** [comment]
@vidarmehr @porchard thanks for the super quick replies! It indeed worked now I downloaded the entire output directory.
