### ISSUE TITLE
Error opening terminal: xterm-256color

### ISSUE THREAD

**Issue by IanCodes** [ParkerLab/ataqv#30]
Hello,

I have just installed ataqv on Ubuntu 20.04:
`sudo apt install ./ataqv_1.3.0-1_amd64.deb`

However, when I try to run it I get the following error:
`Error opening terminal: xterm-256color.`

Command line used:
`ataqv --peak-file AA1_summit_regions_qval.bed --name AA1 --metrics-file AA1.json.gz --excluded-region-file mm39_from_mm10_v2_blacklist.bed --tss-file knownCanonical_GencodeVM27_mm39_TSS.bed --ignore-read-groups mouse AA1.bam > AA1.ataqv.out`

If I run `ataqv -h` I successfully get the help page.

Any thoughts?

Thanks,
Ian

**Comment by IanCodes** [comment]
Looks like I have solved it myself.  The work around was to change the TERM env variable for the session:
`export TERM="xterm"`

**Comment by porchard** [comment]
Indeed, that should do it -- glad you solved this.
