### ISSUE TITLE
reference data in the plots

### ISSUE THREAD

**Issue by crazyhottommy** [ParkerLab/ataqv#5]
Hi there,

I saw a red line representing the reference data in the PLOTS session. what is the reference?
Do you have a SRR number that I can download from GEO?

Thank you!
Tommy

**Comment by ciuin** [comment]
The reference is described in the plot help, but it is kind of buried. Click on the question mark in the controls next to the plot. Toward the bottom will be a paragraph saying something like "The dashed red line is the reference fragment length distribution (the fragment length distribution from SRR891268)." 

That's from our demo, and if you didn't specify a different reference when you built your viewer instance, your reference will also be SRR891268. There's more information on how to configure the reference in the mkarv help; just run `mkarv --help`.

**Comment by umijh** [comment]
The reference is described in the plot help, but it is kind of buried. Click on the question mark in the controls next to the plot. Toward the bottom will be a paragraph saying something like "The dashed red line is the reference fragment length distribution (the fragment length distribution from SRR891268)."

That's from our demo, and if you didn't specify a different reference when you built your viewer instance, your reference will also be SRR891268. There's more information on how to configure the reference in the mkarv help; just run mkarv --help.

**Comment by crazyhottommy** [comment]
Thank you very much for the info!
