### ISSUE TITLE
Please release ataqv_1.1.1

### ISSUE THREAD

**Issue by naumenko-sa** [ParkerLab/ataqv#9]
Hello!

We are installing ataqv via bioconda and getting v1.0.0 which has some bugs fixed in 1.1.1.
Could you please make a release of 1.1.1?

I will then try to push an update to bioconda recipe.
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ataqv/meta.yaml

Thanks!
Sergey

**Comment by roryk** [comment]
+1 to this, if you could cut a new release we can update the bioconda recipe and everyone can be current. bioconda will update automatically!

**Comment by porchard** [comment]
v. 1.1.1 released. Thanks @umijh!.

**Comment by roryk** [comment]
Thanks so much, this is so helpful! The bioconda bot picked it up and I merged the new version in: https://github.com/bioconda/bioconda-recipes/pull/19629
